# Generated by Django 5.2.7 on 2025-12-14 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(help_text='RUC de la empresa (formato: 12345678-9)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener formato: 12345678-9', regex='^\\d{8}-\\d{1}$')])),
                ('nombre', models.CharField(help_text='Nombre o razón social de la empresa', max_length=200)),
                ('sector', models.CharField(help_text='Sector económico (ej: Tecnología, Retail)', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección física', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la empresa está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ruc'], name='empresas_em_ruc_a40d0b_idx'), models.Index(fields=['nombre'], name='empresas_em_nombre_fd766a_idx'), models.Index(fields=['activo'], name='empresas_em_activo_ab1981_idx')],
            },
        ),
    ]
